ignore:
  - "**/test/*"
  - "**/test/**/*"

component_management:
  individual_components:
    - component_id: package1
      name: Package 1
      paths:
        - package1/**
    - component_id: package2
      name: Package 2
      paths:
        - package2/**
