name: Echo PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  echo-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Labels
        run: |
          echo "PR Labels:"
          echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | jq -r '.[]'
      - name: Echo contain hello
        run: |
            echo "Contain hello: ${{ contains(github.event.pull_request.labels.*.name, 'hello') }}"