name: Echo

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  echo-strategy:
    runs-on: ${{ matrix.runner }}
    env:
      SKIP: ${{ matrix.name == 'world' && contains(github.event.pull_request.labels.*.name, 'skip-world') }}
    strategy:
      matrix:
        name: [hello, world]
        runner: [ubuntu-latest]

    steps:
      - name: Echo SKIP
        run: echo "SKIP is ${{ env.SKIP }}"

      - name: Echo strategy
        if: ${{ env.SKIP != 'true' }}
        run: echo "Running on ${{ runner.os }} with ${{ matrix.name }}"
