name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov python3-colcon-lcov-result

      - name: Build
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --symlink-install --cmake-args -DBUILD_TESTING=true -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage -fno-elide-constructors -fno-default-inline' -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage -fno-elide-constructors -fno-default-inline'

      - name: Initial LCOV
        run: |
          . /opt/ros/humble/setup.sh
          . install/setup.sh
          colcon lcov-result --zero-counters
          colcon lcov-result --initial

      - name: Test
        run: |
          . /opt/ros/humble/setup.sh
          . install/setup.sh
          colcon test

      - name: Generate LCOV report
        run: |
          . /opt/ros/humble/setup.sh
          . install/setup.sh
          colcon lcov-result --filter "*/test/*"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          verbose: true
          flags: total
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy lcov reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lcov