name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
          pip install colcon-lcov-result

      - name: Build
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          colcon build --symlink-install --cmake-args -DBUILD_TESTING=true -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'

      - name: Initial LCOV
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          . install/setup.sh
          colcon lcov-result --initial

      - name: Test
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          . install/setup.sh
          colcon test

      - name: Generate LCOV report
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          . install/setup.sh
          colcon lcov-result --filter "*/test/*"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
